"""
cluster_vs_T.py

Perform K-means clustering in latent space and analyze how cluster
membership probabilities vary as a function of temperature.

This script:
    1. Loads latent vectors z (N, D) and corresponding temperatures T (N,)
       generated by latent_extraction.py.
    2. Applies K-means clustering in latent space.
    3. Computes temperature-conditional cluster probabilities:

           P_T(cluster = k)

       defined as the fraction of samples at temperature T that
       belong to cluster k.
    4. Saves numerical results and produces a plot of cluster
       probability vs temperature.

Typical use:
    Phase structure analysis in XY / KT transition studies.
    Identifying temperature regions where latent structure changes.

Output:
    - *_cluster_vs_T.npz
    - *_cluster_vs_T.png
"""

import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

import sys
from pathlib import Path

# Add project root (two levels above) to sys.path
# This ensures imports work when executed as a script.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--latent",
        type=str,
        required=True,
        help="Path to npz file generated by latent_extraction.py "
             "(must contain 'z' and 'T').",
    )

    parser.add_argument(
        "--out_dir",
        type=str,
        default=None,
        help="Output directory (default: same directory as latent file).",
    )

    parser.add_argument(
        "--n_clusters",
        type=int,
        default=3,
        help="Number of K-means clusters.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for K-means.",
    )

    args = parser.parse_args()

    latent_path = Path(args.latent)
    if not latent_path.exists():
        raise FileNotFoundError(f"Latent file not found: {latent_path}")

    data = np.load(latent_path)

    if "z" not in data or "T" not in data:
        raise KeyError("NPZ file must contain both 'z' and 'T' arrays.")

    z = data["z"]  # shape (N, D)
    T = data["T"]  # shape (N,)

    print(f"[INFO] z shape = {z.shape}, T shape = {T.shape}")

    try:
        from sklearn.cluster import KMeans
    except ImportError:
        raise ImportError("scikit-learn is required: pip install scikit-learn")

    print(f"[INFO] Running KMeans (n_clusters={args.n_clusters}) ...")

    kmeans = KMeans(
        n_clusters=args.n_clusters,
        random_state=args.seed,
        n_init="auto",
    )

    labels = kmeans.fit_predict(z)  # shape (N,)

    uniq_T = np.unique(T)
    uniq_T_sorted = np.sort(uniq_T)

    nT = len(uniq_T_sorted)
    K = args.n_clusters

    # Compute P_T(k): probability of cluster k at temperature T
    cluster_probs = np.zeros((nT, K), dtype=np.float64)

    for i, t_val in enumerate(uniq_T_sorted):
        mask = (T == t_val)
        labels_t = labels[mask]
        n_t = labels_t.shape[0]

        if n_t == 0:
            continue

        for k in range(K):
            cluster_probs[i, k] = np.sum(labels_t == k) / n_t

        print(f"[INFO] T={t_val}: n={n_t}, probs={cluster_probs[i]}")

    # Determine output directory
    if args.out_dir is None:
        out_dir = latent_path.parent
    else:
        out_dir = Path(args.out_dir)

    out_dir.mkdir(parents=True, exist_ok=True)

    # Save numerical results
    stats_path = out_dir / f"{latent_path.stem}_cluster_vs_T.npz"

    np.savez_compressed(
        stats_path,
        T=uniq_T_sorted,                 # unique sorted temperatures
        cluster_probs=cluster_probs,     # shape (nT, K)
        centers=kmeans.cluster_centers_, # cluster centers in latent space

        # Per-sample information (used for downstream analysis)
        T_samples=T,
        labels=labels,
    )

    print(f"[INFO] Saved cluster statistics to {stats_path}")

    # Plot cluster probability vs temperature
    fig, ax = plt.subplots(figsize=(6, 4))

    for k in range(K):
        ax.plot(
            uniq_T_sorted,
            cluster_probs[:, k],
            marker="o",
            label=f"cluster {k}",
        )

    ax.set_xlabel("Temperature T")
    ax.set_ylabel("P_T(cluster = k)")
    ax.set_title("Cluster Probability vs Temperature")
    ax.set_ylim(-0.05, 1.05)
    ax.grid(True)
    ax.legend()

    plt.tight_layout()

    out_fig = out_dir / f"{latent_path.stem}_cluster_vs_T.png"
    plt.savefig(out_fig, dpi=300)

    print(f"[INFO] Saved plot to {out_fig}")


if __name__ == "__main__":
    main()


"""
Example usage:

python Unsupervised_Machine_Learning/analysis/cluster_vs_T.py \
    --latent Unsupervised_Machine_Learning/results/latent/autoencoder/autoencoder_latent.npz \
    --n_clusters 3
"""
